# Generated by Django 5.2.12 on 2026-03-08 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('incident', 'Incident'), ('near_miss', 'Near Miss'), ('observation', 'Observation')], max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('description', models.TextField()),
                ('corrective_action', models.TextField(blank=True)),
                ('closed', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_entries', to='reports.dailyreport')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
