# Generated by Django 5.2.12 on 2026-03-09 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version_label', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_sets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sets', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plan_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=64)),
                ('user_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='queued', max_length=32)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_payload_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_analysis_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='core.project')),
                ('plan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='preconstruction.planset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanSheet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sheet_number', models.CharField(blank=True, max_length=64)),
                ('discipline', models.CharField(blank=True, max_length=64)),
                ('storage_key', models.CharField(max_length=512)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('sheet_index', models.PositiveIntegerField(default=0)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parse_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('preview_image', models.CharField(blank=True, max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_plan_sheets', to=settings.AUTH_USER_MODEL)),
                ('plan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='preconstruction.planset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sheets', to='core.project')),
            ],
            options={
                'ordering': ('sheet_index', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AnnotationLayer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotation_layers', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_layers', to='core.project')),
                ('plan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_layers', to='preconstruction.planset')),
                ('plan_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_layers', to='preconstruction.plansheet')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AnnotationItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_type', models.CharField(choices=[('point', 'Point'), ('rectangle', 'Rectangle'), ('polygon', 'Polygon'), ('polyline', 'Polyline'), ('text', 'Text')], max_length=32)),
                ('geometry_json', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotation_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_items', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_annotation_items', to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='preconstruction.annotationlayer')),
                ('plan_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_items', to='preconstruction.plansheet')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(max_length=32)),
                ('geometry_json', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('decision_state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=32)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='preconstruction.aianalysisrun')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='core.project')),
                ('accepted_annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_suggestion', to='preconstruction.annotationitem')),
                ('plan_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='preconstruction.plansheet')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='aianalysisrun',
            name='plan_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='preconstruction.plansheet'),
        ),
        migrations.CreateModel(
            name='RevisionSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=32)),
                ('snapshot_payload_json', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revision_snapshots', to=settings.AUTH_USER_MODEL)),
                ('plan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_snapshots', to='preconstruction.planset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_snapshots', to='core.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf_metadata', 'PDF metadata')], max_length=32)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=32)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='core.project')),
                ('plan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='preconstruction.planset')),
                ('revision_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to='preconstruction.revisionsnapshot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TakeoffItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('doors', 'Doors'), ('door_hardware', 'Door hardware'), ('windows', 'Windows'), ('openings', 'Openings'), ('rooms', 'Rooms'), ('plumbing_fixtures', 'Plumbing fixtures'), ('electrical_fixtures', 'Electrical fixtures'), ('concrete_areas', 'Concrete areas'), ('linear_measurements', 'Linear measurements'), ('custom', 'Custom')], default='custom', max_length=64)),
                ('subcategory', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(choices=[('count', 'Count'), ('square_feet', 'Square feet'), ('linear_feet', 'Linear feet'), ('cubic_yards', 'Cubic yards'), ('each', 'Each'), ('custom', 'Custom')], default='count', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cost_code', models.CharField(blank=True, max_length=64)),
                ('bid_package', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_assisted', 'AI assisted')], default='manual', max_length=32)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_takeoff_items', to=settings.AUTH_USER_MODEL)),
                ('plan_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_items', to='preconstruction.planset')),
                ('plan_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_items', to='preconstruction.plansheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_items', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_takeoff_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='annotationitem',
            name='linked_takeoff_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_annotation', to='preconstruction.takeoffitem'),
        ),
    ]
