# Generated by Django 5.2.12 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preconstruction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansheet",
            name="calibrated_height",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="plansheet",
            name="calibrated_unit",
            field=models.CharField(
                choices=[("feet", "Feet"), ("meters", "Meters")],
                default="feet",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="plansheet",
            name="calibrated_width",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
