# Generated by Django 5.2.12 on 2026-03-13 18:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_takeoff_source_annotation(apps, schema_editor):
    AnnotationItem = apps.get_model('preconstruction', 'AnnotationItem')
    TakeoffItem = apps.get_model('preconstruction', 'TakeoffItem')

    for annotation in AnnotationItem.objects.exclude(linked_takeoff_item_id__isnull=True).iterator():
        TakeoffItem.objects.filter(id=annotation.linked_takeoff_item_id).update(source_annotation_id=annotation.id)


def clear_takeoff_source_annotation(apps, schema_editor):
    TakeoffItem = apps.get_model('preconstruction', 'TakeoffItem')
    TakeoffItem.objects.update(source_annotation_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0002_plan_sheet_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoffitem',
            name='source_annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_takeoff_items', to='preconstruction.annotationitem'),
        ),
        migrations.RunPython(backfill_takeoff_source_annotation, clear_takeoff_source_annotation),
    ]
