# Generated by Django 5.2.12 on 2026-03-13 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('preconstruction', '0003_takeoffitem_source_annotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('spec', 'Specification'), ('addendum', 'Addendum'), ('rfi', 'RFI'), ('submittal', 'Submittal'), ('vendor', 'Vendor'), ('scope', 'Scope'), ('other', 'Other')], default='other', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=128)),
                ('file_extension', models.CharField(max_length=16)),
                ('size_bytes', models.BigIntegerField()),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('parse_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('parse_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_documents', to=settings.AUTH_USER_MODEL)),
                ('plan_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='preconstruction.planset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='preconstruction.projectdocument')),
            ],
            options={
                'ordering': ('document', 'chunk_index'),
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index')],
            },
        ),
    ]
