# Generated by Django 6.0.3 on 2026-03-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='annotations_json',
            field=models.JSONField(blank=True, help_text='Stores overlay data (shapes, text, arrows) for images.', null=True),
        ),
    ]
