# Generated by Django 5.2.12 on 2026-03-08 18:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('weather_source', models.CharField(blank=True, max_length=64)),
                ('weather_summary', models.CharField(blank=True, max_length=255)),
                ('temperature_high_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_low_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wind_max_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_reports', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='core.project')),
            ],
            options={
                'ordering': ('-report_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('review', 'Review'), ('reject', 'Reject'), ('approve', 'Approve'), ('lock', 'Lock'), ('sign', 'Sign')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('signature_intent', models.CharField(blank=True, max_length=255)),
                ('document_hash', models.CharField(blank=True, max_length=128)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='reports.dailyreport')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DelayEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('weather', 'Weather'), ('design', 'Design'), ('delivery', 'Delivery'), ('labor', 'Labor'), ('owner', 'Owner'), ('other', 'Other')], default='other', max_length=32)),
                ('cause', models.CharField(max_length=255)),
                ('impact', models.TextField()),
                ('mitigation', models.TextField(blank=True)),
                ('hours_lost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dailyreport')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('equipment_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('downtime_reason', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dailyreport')),
            ],
            options={
                'ordering': ('equipment_name',),
            },
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('trade', models.CharField(max_length=128)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('workers', models.PositiveIntegerField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_code', models.CharField(blank=True, max_length=64)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dailyreport')),
            ],
            options={
                'ordering': ('trade',),
            },
        ),
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('material_name', models.CharField(max_length=128)),
                ('unit', models.CharField(default='unit', max_length=32)),
                ('quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=128)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dailyreport')),
            ],
            options={
                'ordering': ('material_name',),
            },
        ),
        migrations.CreateModel(
            name='WorkLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('area', models.CharField(max_length=128)),
                ('activity', models.CharField(max_length=255)),
                ('quantity_completed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('schedule_impact', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dailyreport')),
            ],
            options={
                'ordering': ('area', 'activity'),
            },
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_date'), name='unique_project_daily_report'),
        ),
    ]
